stages:
    - build
    - publish
    - publish-utils

default:
    image: docker:latest
    before_script: |
        DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME/main/latest}
        DOCKER_IMAGE_TAG_PREFIX=$DOCKER_IMAGE_TAG-
        DOCKER_IMAGE_TAG_PREFIX=${DOCKER_IMAGE_TAG_PREFIX/latest-/}
        JAVA_VERSIONS=8
        if [ ! -z `command -v docker` ]; then
            echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_USER" ]; then echo -n $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin; fi
        fi
    after_script: |
        if [ ! -z `command -v docker` ]; then
            docker logout $CI_REGISTRY
            if [ -n "$DOCKER_REGISTRY_USER" ]; then docker logout; fi
        fi

build:
    stage: build
    script:
        - for java_version in $JAVA_VERSIONS; do
              docker build . --pull --build-arg JAVA_VERSION=$java_version -t $CI_REGISTRY_IMAGE:${DOCKER_IMAGE_TAG_PREFIX}java$java_version;
              docker push $CI_REGISTRY_IMAGE:${DOCKER_IMAGE_TAG_PREFIX}java$java_version;
          done
        - docker tag $CI_REGISTRY_IMAGE:${DOCKER_IMAGE_TAG_PREFIX}java8 $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
        - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    only:
        - branches
        - tags

publish:
    stage: publish
    script:
        - for java_version in $JAVA_VERSIONS; do
              docker pull $CI_REGISTRY_IMAGE:${DOCKER_IMAGE_TAG_PREFIX}java$java_version;
              docker tag $CI_REGISTRY_IMAGE:${DOCKER_IMAGE_TAG_PREFIX}java$java_version $DOCKER_REGISTRY_USER/$CI_PROJECT_NAME:${DOCKER_IMAGE_TAG_PREFIX}java$java_version;
              docker push $DOCKER_REGISTRY_USER/$CI_PROJECT_NAME:${DOCKER_IMAGE_TAG_PREFIX}java$java_version;
          done
        - docker pull $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
        - docker tag $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG $DOCKER_REGISTRY_USER/$CI_PROJECT_NAME:$DOCKER_IMAGE_TAG
        - docker push $DOCKER_REGISTRY_USER/$CI_PROJECT_NAME:$DOCKER_IMAGE_TAG
    only:
        - main
        - tags

publish-utils:
    stage: publish-utils
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-publish-utils:latest
    script:
        - publish-utils
    only:
        - main
